allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@mantine/carousel@9.3.1"
  - "@mantine/core@9.3.1"
  - "@mantine/dates@9.3.1"
  - "@mantine/form@9.3.1"
  - "@mantine/hooks@9.3.1"
  - "@mantine/notifications@9.3.1"
  - "@mantine/store@9.3.1"
  - "@atlaskit/pragmatic-drag-and-drop-hitbox@2.1.0"
  - dayjs@1.11.23
