/* oxlint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as FaqRouteImport } from "./routes/faq";
import { Route as ImportRouteImport } from "./routes/import";
import { Route as NotificationsRouteImport } from "./routes/notifications";
import { Route as PrivacyRouteImport } from "./routes/privacy";
import { Route as ReleaseCalendarRouteImport } from "./routes/release-calendar";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as TermsRouteImport } from "./routes/terms";
import { Route as AdminReportsRouteImport } from "./routes/admin_.reports";
import { Route as AdminTranslationSuggestionsRouteImport } from "./routes/admin_.translation-suggestions";
import { Route as CollectionIdSlugRouteImport } from "./routes/collection.$id.$slug";
import { Route as CompanyIdSlugRouteImport } from "./routes/company.$id.$slug";
import { Route as GameListIdSlugRouteImport } from "./routes/game-list.$id.$slug";
import { Route as GameIdSlugRouteImport } from "./routes/game.$id.$slug";
import { Route as ProfileIdSlugRouteImport } from "./routes/profile.$id.$slug";
import { Route as GameIdSlugReviewsRouteImport } from "./routes/game_.$id.$slug.reviews";
import { Route as ProfileIdSlugCollectionsRouteImport } from "./routes/profile_.$id.$slug.collections";
import { Route as ProfileIdSlugFriendsRouteImport } from "./routes/profile_.$id.$slug.friends";
import { Route as GameListCompareFirstUserIdFirstUserSlugSecondUserIdSecondUserSlugRouteImport } from "./routes/game-list.compare.$firstUserId.$firstUserSlug.$secondUserId.$secondUserSlug";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const FaqRoute = FaqRouteImport.update({
  id: "/faq",
  path: "/faq",
  getParentRoute: () => rootRouteImport,
} as any);
const ImportRoute = ImportRouteImport.update({
  id: "/import",
  path: "/import",
  getParentRoute: () => rootRouteImport,
} as any);
const NotificationsRoute = NotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const ReleaseCalendarRoute = ReleaseCalendarRouteImport.update({
  id: "/release-calendar",
  path: "/release-calendar",
  getParentRoute: () => rootRouteImport,
} as any);
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: "/admin_/reports",
  path: "/admin/reports",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminTranslationSuggestionsRoute =
  AdminTranslationSuggestionsRouteImport.update({
    id: "/admin_/translation-suggestions",
    path: "/admin/translation-suggestions",
    getParentRoute: () => rootRouteImport,
  } as any);
const CollectionIdSlugRoute = CollectionIdSlugRouteImport.update({
  id: "/collection/$id/$slug",
  path: "/collection/$id/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const CompanyIdSlugRoute = CompanyIdSlugRouteImport.update({
  id: "/company/$id/$slug",
  path: "/company/$id/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const GameListIdSlugRoute = GameListIdSlugRouteImport.update({
  id: "/game-list/$id/$slug",
  path: "/game-list/$id/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const GameIdSlugRoute = GameIdSlugRouteImport.update({
  id: "/game/$id/$slug",
  path: "/game/$id/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileIdSlugRoute = ProfileIdSlugRouteImport.update({
  id: "/profile/$id/$slug",
  path: "/profile/$id/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const GameIdSlugReviewsRoute = GameIdSlugReviewsRouteImport.update({
  id: "/game_/$id/$slug/reviews",
  path: "/game/$id/$slug/reviews",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileIdSlugCollectionsRoute =
  ProfileIdSlugCollectionsRouteImport.update({
    id: "/profile_/$id/$slug/collections",
    path: "/profile/$id/$slug/collections",
    getParentRoute: () => rootRouteImport,
  } as any);
const ProfileIdSlugFriendsRoute = ProfileIdSlugFriendsRouteImport.update({
  id: "/profile_/$id/$slug/friends",
  path: "/profile/$id/$slug/friends",
  getParentRoute: () => rootRouteImport,
} as any);
const GameListCompareFirstUserIdFirstUserSlugSecondUserIdSecondUserSlugRoute =
  GameListCompareFirstUserIdFirstUserSlugSecondUserIdSecondUserSlugRouteImport.update(
    {
      id: "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug",
      path: "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug",
      getParentRoute: () => rootRouteImport,
    } as any,
  );

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/admin": typeof AdminRoute;
  "/faq": typeof FaqRoute;
  "/import": typeof ImportRoute;
  "/notifications": typeof NotificationsRoute;
  "/privacy": typeof PrivacyRoute;
  "/release-calendar": typeof ReleaseCalendarRoute;
  "/search": typeof SearchRoute;
  "/settings": typeof SettingsRoute;
  "/terms": typeof TermsRoute;
  "/admin/reports": typeof AdminReportsRoute;
  "/admin/translation-suggestions": typeof AdminTranslationSuggestionsRoute;
  "/collection/$id/$slug": typeof CollectionIdSlugRoute;
  "/company/$id/$slug": typeof CompanyIdSlugRoute;
  "/game-list/$id/$slug": typeof GameListIdSlugRoute;
  "/game/$id/$slug": typeof GameIdSlugRoute;
  "/profile/$id/$slug": typeof ProfileIdSlugRoute;
  "/game/$id/$slug/reviews": typeof GameIdSlugReviewsRoute;
  "/profile/$id/$slug/collections": typeof ProfileIdSlugCollectionsRoute;
  "/profile/$id/$slug/friends": typeof ProfileIdSlugFriendsRoute;
  "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug": typeof GameListCompareFirstUserIdFirstUserSlugSecondUserIdSecondUserSlugRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/admin": typeof AdminRoute;
  "/faq": typeof FaqRoute;
  "/import": typeof ImportRoute;
  "/notifications": typeof NotificationsRoute;
  "/privacy": typeof PrivacyRoute;
  "/release-calendar": typeof ReleaseCalendarRoute;
  "/search": typeof SearchRoute;
  "/settings": typeof SettingsRoute;
  "/terms": typeof TermsRoute;
  "/admin/reports": typeof AdminReportsRoute;
  "/admin/translation-suggestions": typeof AdminTranslationSuggestionsRoute;
  "/collection/$id/$slug": typeof CollectionIdSlugRoute;
  "/company/$id/$slug": typeof CompanyIdSlugRoute;
  "/game-list/$id/$slug": typeof GameListIdSlugRoute;
  "/game/$id/$slug": typeof GameIdSlugRoute;
  "/profile/$id/$slug": typeof ProfileIdSlugRoute;
  "/game/$id/$slug/reviews": typeof GameIdSlugReviewsRoute;
  "/profile/$id/$slug/collections": typeof ProfileIdSlugCollectionsRoute;
  "/profile/$id/$slug/friends": typeof ProfileIdSlugFriendsRoute;
  "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug": typeof GameListCompareFirstUserIdFirstUserSlugSecondUserIdSecondUserSlugRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/admin": typeof AdminRoute;
  "/faq": typeof FaqRoute;
  "/import": typeof ImportRoute;
  "/notifications": typeof NotificationsRoute;
  "/privacy": typeof PrivacyRoute;
  "/release-calendar": typeof ReleaseCalendarRoute;
  "/search": typeof SearchRoute;
  "/settings": typeof SettingsRoute;
  "/terms": typeof TermsRoute;
  "/admin_/reports": typeof AdminReportsRoute;
  "/admin_/translation-suggestions": typeof AdminTranslationSuggestionsRoute;
  "/collection/$id/$slug": typeof CollectionIdSlugRoute;
  "/company/$id/$slug": typeof CompanyIdSlugRoute;
  "/game-list/$id/$slug": typeof GameListIdSlugRoute;
  "/game/$id/$slug": typeof GameIdSlugRoute;
  "/profile/$id/$slug": typeof ProfileIdSlugRoute;
  "/game_/$id/$slug/reviews": typeof GameIdSlugReviewsRoute;
  "/profile_/$id/$slug/collections": typeof ProfileIdSlugCollectionsRoute;
  "/profile_/$id/$slug/friends": typeof ProfileIdSlugFriendsRoute;
  "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug": typeof GameListCompareFirstUserIdFirstUserSlugSecondUserIdSecondUserSlugRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$"
    | "/admin"
    | "/faq"
    | "/import"
    | "/notifications"
    | "/privacy"
    | "/release-calendar"
    | "/search"
    | "/settings"
    | "/terms"
    | "/admin/reports"
    | "/admin/translation-suggestions"
    | "/collection/$id/$slug"
    | "/company/$id/$slug"
    | "/game-list/$id/$slug"
    | "/game/$id/$slug"
    | "/profile/$id/$slug"
    | "/game/$id/$slug/reviews"
    | "/profile/$id/$slug/collections"
    | "/profile/$id/$slug/friends"
    | "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/$"
    | "/admin"
    | "/faq"
    | "/import"
    | "/notifications"
    | "/privacy"
    | "/release-calendar"
    | "/search"
    | "/settings"
    | "/terms"
    | "/admin/reports"
    | "/admin/translation-suggestions"
    | "/collection/$id/$slug"
    | "/company/$id/$slug"
    | "/game-list/$id/$slug"
    | "/game/$id/$slug"
    | "/profile/$id/$slug"
    | "/game/$id/$slug/reviews"
    | "/profile/$id/$slug/collections"
    | "/profile/$id/$slug/friends"
    | "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug";
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/admin"
    | "/faq"
    | "/import"
    | "/notifications"
    | "/privacy"
    | "/release-calendar"
    | "/search"
    | "/settings"
    | "/terms"
    | "/admin_/reports"
    | "/admin_/translation-suggestions"
    | "/collection/$id/$slug"
    | "/company/$id/$slug"
    | "/game-list/$id/$slug"
    | "/game/$id/$slug"
    | "/profile/$id/$slug"
    | "/game_/$id/$slug/reviews"
    | "/profile_/$id/$slug/collections"
    | "/profile_/$id/$slug/friends"
    | "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  AdminRoute: typeof AdminRoute;
  FaqRoute: typeof FaqRoute;
  ImportRoute: typeof ImportRoute;
  NotificationsRoute: typeof NotificationsRoute;
  PrivacyRoute: typeof PrivacyRoute;
  ReleaseCalendarRoute: typeof ReleaseCalendarRoute;
  SearchRoute: typeof SearchRoute;
  SettingsRoute: typeof SettingsRoute;
  TermsRoute: typeof TermsRoute;
  AdminReportsRoute: typeof AdminReportsRoute;
  AdminTranslationSuggestionsRoute: typeof AdminTranslationSuggestionsRoute;
  CollectionIdSlugRoute: typeof CollectionIdSlugRoute;
  CompanyIdSlugRoute: typeof CompanyIdSlugRoute;
  GameListIdSlugRoute: typeof GameListIdSlugRoute;
  GameIdSlugRoute: typeof GameIdSlugRoute;
  ProfileIdSlugRoute: typeof ProfileIdSlugRoute;
  GameIdSlugReviewsRoute: typeof GameIdSlugReviewsRoute;
  ProfileIdSlugCollectionsRoute: typeof ProfileIdSlugCollectionsRoute;
  ProfileIdSlugFriendsRoute: typeof ProfileIdSlugFriendsRoute;
  GameListCompareFirstUserIdFirstUserSlugSecondUserIdSecondUserSlugRoute: typeof GameListCompareFirstUserIdFirstUserSlugSecondUserIdSecondUserSlugRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/faq": {
      id: "/faq";
      path: "/faq";
      fullPath: "/faq";
      preLoaderRoute: typeof FaqRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/import": {
      id: "/import";
      path: "/import";
      fullPath: "/import";
      preLoaderRoute: typeof ImportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/notifications": {
      id: "/notifications";
      path: "/notifications";
      fullPath: "/notifications";
      preLoaderRoute: typeof NotificationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy": {
      id: "/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/release-calendar": {
      id: "/release-calendar";
      path: "/release-calendar";
      fullPath: "/release-calendar";
      preLoaderRoute: typeof ReleaseCalendarRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/terms": {
      id: "/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin_/reports": {
      id: "/admin_/reports";
      path: "/admin/reports";
      fullPath: "/admin/reports";
      preLoaderRoute: typeof AdminReportsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin_/translation-suggestions": {
      id: "/admin_/translation-suggestions";
      path: "/admin/translation-suggestions";
      fullPath: "/admin/translation-suggestions";
      preLoaderRoute: typeof AdminTranslationSuggestionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/collection/$id/$slug": {
      id: "/collection/$id/$slug";
      path: "/collection/$id/$slug";
      fullPath: "/collection/$id/$slug";
      preLoaderRoute: typeof CollectionIdSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/company/$id/$slug": {
      id: "/company/$id/$slug";
      path: "/company/$id/$slug";
      fullPath: "/company/$id/$slug";
      preLoaderRoute: typeof CompanyIdSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/game-list/$id/$slug": {
      id: "/game-list/$id/$slug";
      path: "/game-list/$id/$slug";
      fullPath: "/game-list/$id/$slug";
      preLoaderRoute: typeof GameListIdSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/game/$id/$slug": {
      id: "/game/$id/$slug";
      path: "/game/$id/$slug";
      fullPath: "/game/$id/$slug";
      preLoaderRoute: typeof GameIdSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile/$id/$slug": {
      id: "/profile/$id/$slug";
      path: "/profile/$id/$slug";
      fullPath: "/profile/$id/$slug";
      preLoaderRoute: typeof ProfileIdSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/game_/$id/$slug/reviews": {
      id: "/game_/$id/$slug/reviews";
      path: "/game/$id/$slug/reviews";
      fullPath: "/game/$id/$slug/reviews";
      preLoaderRoute: typeof GameIdSlugReviewsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile_/$id/$slug/collections": {
      id: "/profile_/$id/$slug/collections";
      path: "/profile/$id/$slug/collections";
      fullPath: "/profile/$id/$slug/collections";
      preLoaderRoute: typeof ProfileIdSlugCollectionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile_/$id/$slug/friends": {
      id: "/profile_/$id/$slug/friends";
      path: "/profile/$id/$slug/friends";
      fullPath: "/profile/$id/$slug/friends";
      preLoaderRoute: typeof ProfileIdSlugFriendsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug": {
      id: "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug";
      path: "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug";
      fullPath: "/game-list/compare/$firstUserId/$firstUserSlug/$secondUserId/$secondUserSlug";
      preLoaderRoute: typeof GameListCompareFirstUserIdFirstUserSlugSecondUserIdSecondUserSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  FaqRoute: FaqRoute,
  ImportRoute: ImportRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ReleaseCalendarRoute: ReleaseCalendarRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTranslationSuggestionsRoute: AdminTranslationSuggestionsRoute,
  CollectionIdSlugRoute: CollectionIdSlugRoute,
  CompanyIdSlugRoute: CompanyIdSlugRoute,
  GameListIdSlugRoute: GameListIdSlugRoute,
  GameIdSlugRoute: GameIdSlugRoute,
  ProfileIdSlugRoute: ProfileIdSlugRoute,
  GameIdSlugReviewsRoute: GameIdSlugReviewsRoute,
  ProfileIdSlugCollectionsRoute: ProfileIdSlugCollectionsRoute,
  ProfileIdSlugFriendsRoute: ProfileIdSlugFriendsRoute,
  GameListCompareFirstUserIdFirstUserSlugSecondUserIdSecondUserSlugRoute:
    GameListCompareFirstUserIdFirstUserSlugSecondUserIdSecondUserSlugRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
